In [1]:
import pandas as pd

df = pd.read_csv("/workspaces/data-science/top10s.csv", encoding='ISO-8859-1')

dfs = pd.read_csv('/workspaces/data-science/SpotifyTopSongsByCountry - May 2020.csv', encoding='ISO-8859-1')

# cabeca1 = df.head()

# print(cabeca1)

# cabeca2 = dfs.head()

# print(cabeca2)

# rabo = df.tail(10)

# print(rabo)

# print(df.info)

# print(df.dtypes)

# print(df.select_dtypes(include='object'))

# print(df.describe)

# print(df.isna().sum())

# print(df['artist'].unique())

# print(df['artist'].nunique())

# print(df.shape)

# print(df.size)

# print(df.columns)

# print(df.nsmallest(3, 'bpm'))

# print(df.nlargest(3, 'bpm'))

df_ops=df.drop_duplicates(subset=['title'], keep='last')

# print(df_ops)

# print(df.query("artist == 'Ariana Grande'"))

# print(df.query('dur > 200'))

df_ops.drop(columns=['spch'], inplace=True)

print(df_ops)

     Unnamed: 0                                              title  \
0             1                                   Hey, Soul Sister
1             2                               Love The Way You Lie
2             3                                            TiK ToK
3             4                                        Bad Romance
5             6                                               Baby
..          ...                                                ...
598         599                Find U Again (feat. Camila Cabello)
599         600      Cross Me (feat. Chance the Rapper & PnB Rock)
600         601  No Brainer (feat. Justin Bieber, Chance the Ra...
601         602    Nothing Breaks Like a Heart (feat. Miley Cyrus)
602         603                                   Kills You Slowly

               artist        top genre  year  bpm  nrgy  dnce  dB  live  val  \
0               Train       neo mellow  2010   97    89    67  -4     8   80
1              Eminem  detroit hip hop  2010   87    93    75  -5    52   64
2               Kesha        dance pop  2010  120    84    76  -3    29   71
3           Lady Gaga        dance pop  2010  119    92    70  -4     8   71
5       Justin Bieber     canadian pop  2010   65    86    73  -5    11   54
..                ...              ...   ...  ...   ...   ...  ..   ...  ...
598       Mark Ronson        dance pop  2019  104    66    61  -7    20   16
599        Ed Sheeran              pop  2019   95    79    75  -6     7   61
600         DJ Khaled        dance pop  2019  136    76    53  -5     9   65
601       Mark Ronson        dance pop  2019  114    79    60  -6    42   24
602  The Chainsmokers       electropop  2019  150    44    70  -9    13   23

     dur  acous  pop
0    217     19   83
1    263     24   82
2    200     10   80
3    295      0   79
5    214      4   77
..   ...    ...  ...
598  176      1   75
599  206     21   75
600  260      7   70
601  217      1   69
602  213      6   67

[584 rows x 14 columns]

<ipython-input-1-2cd12e9a4eef>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ops.drop(columns=['spch'], inplace=True)

In [2]:
df_ops['dur'].mean()

224.63698630136986

In [3]:
df_ops['dur'].min()

134

In [4]:
df_ops['dur'].max()

424

In [5]:
df.agg({'acous':'mean', 'dur': 'max'})

acous     14.3267
dur      424.0000
dtype: float64

In [6]:
df_ops['dur'].cumsum()

0         217
1         480
2         680
3         975
5        1189
        ...
598    130292
599    130498
600    130758
601    130975
602    131188
Name: dur, Length: 584, dtype: int64

In [7]:
df_ops.sort_values(by='dur',ascending=False)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop
188,189,TKO,Justin Timberlake,dance pop,2013,138,68,61,-7,43,49,424,1,58
422,423,Wish That You Were Here - From ï¿½Miss Peregri...,Florence + The Machine,art pop,2016,94,57,37,-6,13,12,403,72,57
63,64,Monster,Kanye West,chicago rap,2011,125,69,63,-6,67,10,379,0,73
162,163,Lose Yourself to Dance,Daft Punk,electro,2013,100,66,83,-8,8,67,354,8,72
194,195,Take Back the Night,Justin Timberlake,dance pop,2013,107,66,59,-5,64,33,353,4,54
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
581,582,Good as Hell (feat. Ariana Grande) - Remix,Lizzo,escape room,2019,96,89,67,-3,74,48,159,30,90
492,493,Reality (feat. Janieck Devy) - Radio Edit,Lost Frequencies,belgian edm,2017,122,64,73,-7,8,53,158,2,59
174,175,I Love It (feat. Charli XCX),Icona Pop,candy pop,2013,126,91,71,-3,15,82,157,1,67
591,592,All Around The World (La La La),R3HAB,big room,2019,125,86,73,-5,11,52,148,48,82
330,331,Mark My Words,Justin Bieber,canadian pop,2015,114,26,38,-9,17,52,134,88,63

In [8]:
df['year'].astype(str)

0      2010
1      2010
2      2010
3      2010
4      2010
       ...
598    2019
599    2019
600    2019
601    2019
602    2019
Name: year, Length: 603, dtype: object

In [9]:
pd.get_dummies(df,columns=['artist'])

,Unnamed: 0,title,top genre,year,bpm,nrgy,dnce,dB,live,val,...,artist_Train,artist_Troye Sivan,artist_Usher,artist_Wiz Khalifa,artist_Years & Years,artist_ZAYN,artist_Zara Larsson,artist_Zedd,artist_fun.,artist_will.i.am
0,1,"Hey, Soul Sister",neo mellow,2010,97,89,67,-4,8,80,...,True,False,False,False,False,False,False,False,False,False
1,2,Love The Way You Lie,detroit hip hop,2010,87,93,75,-5,52,64,...,False,False,False,False,False,False,False,False,False,False
2,3,TiK ToK,dance pop,2010,120,84,76,-3,29,71,...,False,False,False,False,False,False,False,False,False,False
3,4,Bad Romance,dance pop,2010,119,92,70,-4,8,71,...,False,False,False,False,False,False,False,False,False,False
4,5,Just the Way You Are,pop,2010,109,84,64,-5,9,43,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),dance pop,2019,104,66,61,-7,20,16,...,False,False,False,False,False,False,False,False,False,False
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),pop,2019,95,79,75,-6,7,61,...,False,False,False,False,False,False,False,False,False,False
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",dance pop,2019,136,76,53,-5,9,65,...,False,False,False,False,False,False,False,False,False,False
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),dance pop,2019,114,79,60,-6,42,24,...,False,False,False,False,False,False,False,False,False,False
602,603,Kills You Slowly,electropop,2019,150,44,70,-9,13,23,...,False,False,False,False,False,False,False,False,False,False

In [10]:
df_ops.assign()

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,79
5,6,Baby,Justin Bieber,canadian pop,2010,65,86,73,-5,11,54,214,4,77
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,16,176,1,75
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,61,206,21,75
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,65,260,7,70
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,24,217,1,69
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,23,213,6,67

In [11]:
df_ops.assing(energy_dance= lambda df: df['dnce']*df['nrgy'])

AttributeError: 'DataFrame' object has no attribute 'assing'

In [1]:
df.groupby('artist').count()

NameError: name 'df' is not defined

In [2]:
df.groupby('artist').count()

NameError: name 'df' is not defined

In [3]:
df = pd.read_csv("/workspaces/data-science/top10s.csv", encoding='ISO-8859-1')

NameError: name 'pd' is not defined

In [4]:
import pandas as pd

df = pd.read_csv("/workspaces/data-science/top10s.csv", encoding='ISO-8859-1')

dfs = pd.read_csv('/workspaces/data-science/SpotifyTopSongsByCountry - May 2020.csv', encoding='ISO-8859-1')

# cabeca1 = df.head()

# print(cabeca1)

# cabeca2 = dfs.head()

# print(cabeca2)

# rabo = df.tail(10)

# print(rabo)

# print(df.info)

# print(df.dtypes)

# print(df.select_dtypes(include='object'))

# print(df.describe)

# print(df.isna().sum())

# print(df['artist'].unique())

# print(df['artist'].nunique())

# print(df.shape)

# print(df.size)

# print(df.columns)

# print(df.nsmallest(3, 'bpm'))

# print(df.nlargest(3, 'bpm'))

df_ops=df.drop_duplicates(subset=['title'], keep='last')

# print(df_ops)

# print(df.query("artist == 'Ariana Grande'"))

# print(df.query('dur > 200'))

df_ops.drop(columns=['spch'], inplace=True)

print(df.groupby('artist').count())

                     Unnamed: 0  title  top genre  year  bpm  nrgy  dnce  dB  \
artist
3OH!3                         1      1          1     1    1     1     1   1
5 Seconds of Summer           1      1          1     1    1     1     1   1
A Great Big World             1      1          1     1    1     1     1   1
Adam Lambert                  2      2          2     2    2     2     2   2
Adele                        10     10         10    10   10    10    10  10
...                         ...    ...        ...   ...  ...   ...   ...  ..
ZAYN                          5      5          5     5    5     5     5   5
Zara Larsson                  1      1          1     1    1     1     1   1
Zedd                          6      6          6     6    6     6     6   6
fun.                          2      2          2     2    2     2     2   2
will.i.am                     1      1          1     1    1     1     1   1

                     live  val  dur  acous  spch  pop
artist
3OH!3                   1    1    1      1     1    1
5 Seconds of Summer     1    1    1      1     1    1
A Great Big World       1    1    1      1     1    1
Adam Lambert            2    2    2      2     2    2
Adele                  10   10   10     10    10   10
...                   ...  ...  ...    ...   ...  ...
ZAYN                    5    5    5      5     5    5
Zara Larsson            1    1    1      1     1    1
Zedd                    6    6    6      6     6    6
fun.                    2    2    2      2     2    2
will.i.am               1    1    1      1     1    1

[184 rows x 14 columns]

<ipython-input-4-c7db7da6f8b9>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ops.drop(columns=['spch'], inplace=True)

In [5]:
df.groupby('artist')['title'].count()

artist
3OH!3                   1
5 Seconds of Summer     1
A Great Big World       1
Adam Lambert            2
Adele                  10
                       ..
ZAYN                    5
Zara Larsson            1
Zedd                    6
fun.                    2
will.i.am               1
Name: title, Length: 184, dtype: int64

In [6]:
df.groupby(['artist', 'year'])['title'].count()

artist               year
3OH!3                2010    1
5 Seconds of Summer  2014    1
A Great Big World    2014    1
Adam Lambert         2010    2
Adele                2011    2
                            ..
Zedd                 2015    1
                     2016    1
                     2017    2
fun.                 2012    2
will.i.am            2013    1
Name: title, Length: 409, dtype: int64

In [7]:
df.groupby('artist').agg({'year':'count', 'dur':'mean'})

                     year    dur
artist
3OH!3                   1  192.0
5 Seconds of Summer     1  202.0
A Great Big World       1  229.0
Adam Lambert            2  227.5
Adele                  10  257.5
...                   ...    ...
ZAYN                    5  213.0
Zara Larsson            1  213.0
Zedd                    6  228.0
fun.                    2  264.0
will.i.am               1  280.0

[184 rows x 2 columns]

In [8]:
df_grouped_year=df.groupby('year')

In [9]:
df_grouped_year.ngroups

10

In [10]:
df_grouped_year.groups

{2010: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50], 2011: [51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103], 2012: [104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138], 2013: [139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209], 2014: [210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267], 2015: [268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362], 2016: [363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442], 2017: [443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507], 2018: [508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571], 2019: [572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602]}

In [11]:
df_grouped_year.size()

year
2010    51
2011    53
2012    35
2013    71
2014    58
2015    95
2016    80
2017    65
2018    64
2019    31
dtype: int64

In [12]:
df_grouped_year.get_group(2015)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
268,269,Thinking out Loud,Ed Sheeran,pop,2015,79,45,78,-6,18,59,282,47,3,84
269,270,I'm Not The Only One,Sam Smith,pop,2015,82,49,68,-6,8,49,239,53,4,84
270,271,The Hills,The Weeknd,canadian contemporary r&b,2015,113,56,58,-7,14,14,242,7,5,84
271,272,Love Yourself,Justin Bieber,canadian pop,2015,100,38,61,-10,28,52,234,84,44,83
272,273,Uptown Funk,Mark Ronson,dance pop,2015,115,61,86,-7,3,93,270,1,8,82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
358,359,Spark The Fire,Gwen Stefani,dance pop,2015,120,80,88,-4,20,54,202,8,6,39
359,360,Run Run Run,Kelly Clarkson,dance pop,2015,112,37,28,-7,11,8,273,45,4,36
360,361,Let Me Be Your Lover,Enrique Iglesias,dance pop,2015,112,90,72,-4,6,88,238,1,13,34
361,362,Dangerous,Jennifer Hudson,dance pop,2015,109,53,90,-5,8,65,255,0,5,18
362,363,L.A.LOVE (la la),Fergie,dance pop,2015,202,39,48,-8,26,27,193,2,9,0

In [13]:
df.head()

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,val,dur,acous,spch,pop
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,80,217,19,4,83
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,64,263,24,23,82
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,71,200,10,14,80
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,71,295,0,4,79
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,43,221,2,4,78

In [14]:
dfs.head()

,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,Global,Global,1,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),0,3:02
1,Global,Global,2,Blinding Lights,The Weeknd,After Hours,0,3:20
2,Global,Global,3,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01
3,Global,Global,4,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
4,Global,Global,5,Toosie Slide,Drake,Dark Lane Demo Tapes,1,4:07

In [15]:
df.merge(dfs,left_on='artist',right_on='artists',how='left')

KeyError: 'artists'

In [16]:
df.merge(dfs,left_on='artist',right_on='artist',how='left')

KeyError: 'artist'

In [17]:
df.merge(dfs,left_on='artist',right_on='Artists',how='left')

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,spch,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,4,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,23,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,14,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,4,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,4,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1858,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,3,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1859,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,12,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,34,70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1861,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,7,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1862,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,6,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
df.merge(dfs,left_on='artist',right_on='Artists',how='left').fillna(0)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,spch,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,4,83,0,0,0.0,0,0,0,0.0,0
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,23,82,0,0,0.0,0,0,0,0.0,0
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,14,80,0,0,0.0,0,0,0,0.0,0
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,4,79,0,0,0.0,0,0,0,0.0,0
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,4,78,0,0,0.0,0,0,0,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1858,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,3,75,0,0,0.0,0,0,0,0.0,0
1859,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,12,75,0,0,0.0,0,0,0,0.0,0
1860,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,34,70,0,0,0.0,0,0,0,0.0,0
1861,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,7,69,0,0,0.0,0,0,0,0.0,0
1862,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,6,67,0,0,0.0,0,0,0,0.0,0

In [19]:
df.merge(dfs,left_on='artist',right_on='Artists',how='left', indicator=True)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration,_merge
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1858,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1859,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1860,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,70,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1861,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,69,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1862,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [20]:
df.join(dfs)

,Unnamed: 0,title,artist,top genre,year,bpm,nrgy,dnce,dB,live,...,spch,pop,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,1,"Hey, Soul Sister",Train,neo mellow,2010,97,89,67,-4,8,...,4,83,Global,Global,1,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),0,3:02
1,2,Love The Way You Lie,Eminem,detroit hip hop,2010,87,93,75,-5,52,...,23,82,Global,Global,2,Blinding Lights,The Weeknd,After Hours,0,3:20
2,3,TiK ToK,Kesha,dance pop,2010,120,84,76,-3,29,...,14,80,Global,Global,3,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01
3,4,Bad Romance,Lady Gaga,dance pop,2010,119,92,70,-4,8,...,4,79,Global,Global,4,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
4,5,Just the Way You Are,Bruno Mars,pop,2010,109,84,64,-5,9,...,4,78,Global,Global,5,Toosie Slide,Drake,Dark Lane Demo Tapes,1,4:07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
598,599,Find U Again (feat. Camila Cabello),Mark Ronson,dance pop,2019,104,66,61,-7,20,...,3,75,Costa Rica,North America,49,The Box,Roddy Ricch,Please Excuse Me For Being Antisocial,1,3:16
599,600,Cross Me (feat. Chance the Rapper & PnB Rock),Ed Sheeran,pop,2019,95,79,75,-6,7,...,12,75,Costa Rica,North America,50,CANCIÃN CON YANDEL,"Yandel, Bad Bunny",LAS QUE NO IBAN A SALIR,1,3:29
600,601,"No Brainer (feat. Justin Bieber, Chance the Ra...",DJ Khaled,dance pop,2019,136,76,53,-5,9,...,34,70,Czech Republic,Europe,1,Blinding Lights,The Weeknd,After Hours,0,3:20
601,602,Nothing Breaks Like a Heart (feat. Miley Cyrus),Mark Ronson,dance pop,2019,114,79,60,-6,42,...,7,69,Czech Republic,Europe,2,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
602,603,Kills You Slowly,The Chainsmokers,electropop,2019,150,44,70,-9,13,...,6,67,Czech Republic,Europe,3,GOOBA,6ix9ine,GOOBA,1,2:12

In [21]:
df.append(dfs)

AttributeError: 'DataFrame' object has no attribute 'append'

In [1]:
df.from_records(dfs)

NameError: name 'df' is not defined

In [2]:
import pandas as pd

df = pd.read_csv("/workspaces/data-science/top10s.csv", encoding='ISO-8859-1')

dfs = pd.read_csv('/workspaces/data-science/SpotifyTopSongsByCountry - May 2020.csv', encoding='ISO-8859-1')

# cabeca1 = df.head()

# print(cabeca1)

# cabeca2 = dfs.head()

# print(cabeca2)

# rabo = df.tail(10)

# print(rabo)

# print(df.info)

# print(df.dtypes)

# print(df.select_dtypes(include='object'))

# print(df.describe)

# print(df.isna().sum())

# print(df['artist'].unique())

# print(df['artist'].nunique())

# print(df.shape)

# print(df.size)

# print(df.columns)

# print(df.nsmallest(3, 'bpm'))

# print(df.nlargest(3, 'bpm'))

df_ops=df.drop_duplicates(subset=['title'], keep='last')

# print(df_ops)

# print(df.query("artist == 'Ariana Grande'"))

# print(df.query('dur > 200'))

df_ops.drop(columns=['spch'], inplace=True)

print(df.groupby('artist').count())

                     Unnamed: 0  title  top genre  year  bpm  nrgy  dnce  dB  \
artist
3OH!3                         1      1          1     1    1     1     1   1
5 Seconds of Summer           1      1          1     1    1     1     1   1
A Great Big World             1      1          1     1    1     1     1   1
Adam Lambert                  2      2          2     2    2     2     2   2
Adele                        10     10         10    10   10    10    10  10
...                         ...    ...        ...   ...  ...   ...   ...  ..
ZAYN                          5      5          5     5    5     5     5   5
Zara Larsson                  1      1          1     1    1     1     1   1
Zedd                          6      6          6     6    6     6     6   6
fun.                          2      2          2     2    2     2     2   2
will.i.am                     1      1          1     1    1     1     1   1

                     live  val  dur  acous  spch  pop
artist
3OH!3                   1    1    1      1     1    1
5 Seconds of Summer     1    1    1      1     1    1
A Great Big World       1    1    1      1     1    1
Adam Lambert            2    2    2      2     2    2
Adele                  10   10   10     10    10   10
...                   ...  ...  ...    ...   ...  ...
ZAYN                    5    5    5      5     5    5
Zara Larsson            1    1    1      1     1    1
Zedd                    6    6    6      6     6    6
fun.                    2    2    2      2     2    2
will.i.am               1    1    1      1     1    1

[184 rows x 14 columns]

<ipython-input-2-c7db7da6f8b9>:51: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_ops.drop(columns=['spch'], inplace=True)

In [3]:
df.from_records(dfs)

<ipython-input-3-31cb333fa39a>:1: FutureWarning: Passing a DataFrame to DataFrame.from_records is deprecated. Use set_index and/or drop to modify the DataFrame instead.
  df.from_records(dfs)

,Country,Continent,Rank,Title,Artists,Album,Explicit,Duration
0,Global,Global,1,Rain On Me (with Ariana Grande),"Lady Gaga, Ariana Grande",Rain On Me (with Ariana Grande),0,3:02
1,Global,Global,2,Blinding Lights,The Weeknd,After Hours,0,3:20
2,Global,Global,3,ROCKSTAR (feat. Roddy Ricch),"DaBaby, Roddy Ricch",BLAME IT ON BABY,1,3:01
3,Global,Global,4,Roses - Imanbek Remix,"SAINt JHN, Imanbek",Roses (Imanbek Remix),1,2:56
4,Global,Global,5,Toosie Slide,Drake,Dark Lane Demo Tapes,1,4:07
...,...,...,...,...,...,...,...,...
3145,Vietnam,Asia,46,ÄÃ Tá»ªNG LÃ,VÅ©.,ÄÃ Tá»ªNG LÃ,0,4:20
3146,Vietnam,Asia,47,MÆ°á»£n RÆ°á»£u Tá» TÃ¬nh,"BigDaddy, Emily",MÆ°á»£n RÆ°á»£u Tá» TÃ¬nh,0,3:18
3147,Vietnam,Asia,48,NgÃ y Táº­n Tháº¿,"TÃ³c TiÃªn, Da LAB, Touliver",NgÃ y Táº­n Tháº¿,0,3:52
3148,Vietnam,Asia,49,Äi Äu ÄÆ°a Äi,Bich Phuong,Äi Äu ÄÆ°a Äi,0,3:40
3149,Vietnam,Asia,50,Blinding Lights,The Weeknd,After Hours,0,3:20

In [4]:
df[:10].style.background_gradient(axis=0, cmap='YlOrRd')